export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import Hero from "@/components/Hero";
import Section1 from "@/components/section1.jsx";
import Section2 from "@/components/Section2";
import Section3 from "@/components/Section3";
import Section4 from "@/components/Section4";
import Section5 from "@/components/Section5";

export default function Home() {
  return (
    <div className="">
    
      <Hero />
      <Section1 />
      <Section2 />
      <Section3/>
      <Section4/>
      <Section5/>
    </div>
  );
}
